### ISSUE TITLE
A small web-app to quickly test our models on the new images

### ISSUE THREAD

**Issue by sayakpaul** [vaishleshik/histology_classifier#3]
Hi, @magus96 @cmacus I made this little web application (https://histology-classification.onrender.com/) to make it convenient for ourselves to test our models on the new images. The code is pushed [here](https://github.com/vaishleshik/Histology-Classification-Deployment).

Here's a demo as well: https://www.loom.com/share/2b36fd8bad7e4d08a6c38c7f91b9ca4b

I hope this proves to be handy.

**Comment by magus96** [comment]
This is great, good job! Just a heads up, Google Colab just got the new T4 GPUs, they come with special tensor cores for mixed precision training, so you can head over there and retrain the model.

**Comment by sayakpaul** [comment]
Thanks for the heads u, but I have got this already: 

![image](https://user-images.githubusercontent.com/22957388/56791866-c6ce5380-6825-11e9-90b7-de5d08f8ac75.png)

**Comment by magus96** [comment]
These are TPUs right? The new T4 is a GPU which some Tensor cores. Will drastically reduce the compute time. And this is free forever.

**Comment by sayakpaul** [comment]
Yes,  TPUs

I experimented in the latest Colab yesterday and yes,  some blazing differences in the times.
